export class AppError extends Error {
  constructor(
    public statusCode: number,
    public errorCode: string,
    message: string
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export const ErrorCodes = {
  INVALID_PATIENT_ID: 'INVALID_PATIENT_ID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EMR_SYSTEM_ERROR: 'EMR_SYSTEM_ERROR',
  DATA_CONVERSION_ERROR: 'DATA_CONVERSION_ERROR',
  DATA_VALIDATION_ERROR: 'DATA_VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
  GENERATION_ERROR: 'GENERATION_ERROR',
  GENERATION_TIMEOUT: 'GENERATION_TIMEOUT',
  TEMPLATE_ERROR: 'TEMPLATE_ERROR',
  SAVE_ERROR: 'SAVE_ERROR',
  CONTENT_VALIDATION_ERROR: 'CONTENT_VALIDATION_ERROR',
  SUMMARY_NOT_FOUND: 'SUMMARY_NOT_FOUND',
  EDIT_PERMISSION_DENIED: 'EDIT_PERMISSION_DENIED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  APPROVAL_PERMISSION_DENIED: 'APPROVAL_PERMISSION_DENIED',
  ALREADY_APPROVED: 'ALREADY_APPROVED',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  EMR_SEND_ERROR: 'EMR_SEND_ERROR',
  PDF_GENERATION_ERROR: 'PDF_GENERATION_ERROR',
} as const;

